### ISSUE TITLE
No section given for 'PACKAGE NAME', skipping.

### ISSUE THREAD

**Issue by xlionjuan** [morph027/apt-repo-action#5]
When I `wget` a `.deb` files from Github, it return this error, how to specify section?

**Comment by morph027** [comment]
How was the package created? Using nfpm probably? This is not a problem of the repo but with the package file. You should specify a section for the package when building it.

**Comment by xlionjuan** [comment]
so....I can't just specify "section" without modify the package

```
Package: rustdesk
Version: 1.3.0
Architecture: amd64
Maintainer: rustdesk <info@rustdesk.com>
Homepage: https://rustdesk.com
Depends: libgtk-3-0, libxcb-randr0, libxdo3, libxfixes3, libxcb-shape0, libxcb-xfixes0, libasound2, libsystemd0, curl, libva-drm2, libva-x11-2, libvdpau1, libgstreamer-plugins-base1.0-0, libpam0g, libappindicator3-1, gstreamer1.0-pipewire
Description: A remote control software.
```

**Comment by morph027** [comment]
Okay, figured out we need an override file for this.

I'll add support for this.

- [ ] add new parameter `override`
- [ ] if `override` is existing file, add `DebOverride: ${override}` to `conf/distributions` and copy `${override}` file from source dir into repo dir.
- [ ] add to README
- [ ] create new release

Example file:

```
rustdesk Section main
rustdesk Priority optional
```

**Comment by morph027** [comment]
Can you try with actions latest changes from `main` branch?

```
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: morph027/apt-repo-action@main
        with:
          ...
          override: ./override # the location of the file within your repo, thats why checkout is needed before
```

Then, in your repo create an override file. Example `override`:

```
rustdesk Section main
rustdesk Priority optional
```

**Comment by xlionjuan** [comment]
I don't know what is happening

I run
```
wget -O rustdesk.deb https://github.com/rustdesk/rustdesk/releases/download/1.3.0/rustdesk-1.3.0-x86_64.deb
pwd
ls
```
to check the directory is correct

Result:
```
2024-09-19 02:18:12 (68.7 MB/s) - ‘rustdesk.deb’ saved [19385572/19385572]

/home/runner/work/apt-repo/apt-repo
README.md
override
rustdesk.deb
```




```yaml
- uses: morph027/apt-repo-action@main
          id: create-apt-repo
          with:
            repo-name: ${{ env.REPO_NAME }}
            signing-key: ${{ secrets.SIGNING_KEY }}
            codename: ${{ env.CODENAME }}
            components: ${{ env.COMPONENTS }}
            architectures: ${{ env.ARCHITECTURES }}
            override: ./override # the location of the file within your repo, thats why checkout is needed before
```

https://github.com/xlionjuan/apt-repo/actions/runs/10933257506/job/30351423381
https://github.com/xlionjuan/apt-repo
